Sinatra メモアプリ完成
choco0809/sinatra pull request #1
Opened 2022-04-23 23:51 UTC by choco0809

お手数ですがご確認のほどよろしくお願い致します🙇‍♂️

2022-04-29 08:23 UTC, u1tnk requested changes

2022-04-29 08:23 UTC, u1tnk commented on memo.rb
> +def sanitize(sanitize_strings)
この処理はruby標準であるのでそちらを使いましょう。以下参照してください。

https://docs.ruby-lang.org/ja/latest/method/CGI/s/escapeHTML.html

2022-04-29 08:23 UTC, u1tnk commented on memo.rb
> +  sanitize(**params)
saniteze処理は XSS対策でやっていると思いますが。データ保存する際は元データを変換してしまうので、そのまま保存して、viewで表示するときにsanitizeするようにしましょう。

2022-04-29 08:23 UTC, u1tnk commented on memo.rb
> +def self_memo(memo_list, id)
これはidに対応するメモを探すものだと思いますが、 `self_memo`だとちょっと分かりづらいです。
ruby/railsの慣習だと find_memoとする方が良いかと思います。

2022-05-03 01:27 UTC, choco0809 commented on memo.rb
> +def sanitize(sanitize_strings)
こんな便利なクラスが存在していたんですね🙇‍♂️
CGIクラスを用いてsanitizeを実装するよう修正しました。

2022-05-03 01:28 UTC, choco0809 commented on memo.rb
> +  sanitize(**params)
sanitize処理の理解が浅かったです🙇‍♂️
データを保存する際にsanitize処理をしてしまうとデータの改竄になってしまいますね...

2022-05-03 01:28 UTC, choco0809 commented on memo.rb
> +def self_memo(memo_list, id)
名前を修正しました🙇‍♂️

2022-05-04 15:19 UTC, u1tnk approved these changes
👍

2022-05-06 01:31 UTC, merged