WebアプリからのDB利用
choco0809/sinatra pull request #2
Opened 2022-05-06 02:31 UTC by choco0809

# WebアプリからのDB利用
ご確認のほどよろしくお願い致します🙇‍♂️

- [x] DB接続は遅い(重い)処理なので使い回せるようにしよう。
- [x] SQL実行時には SQLインジェクション(検索して調べてください)を起こさないようにしましょう。
- [x] SQLインジェクションの解決策はいくつかありますが、「入力文字列をエスケープする」はベストな解決策 ではない （いろいろ問題が起きやすい）です。この方法が解決策のトップに載っていても採用しないようにしてください。

2022-05-11 03:23 UTC, u1tnk requested changes

2022-05-11 03:23 UTC, u1tnk commented on memo.rb
> +def add_memo(params)
データベースでは(普通)insertすると idを採番してくれる機能がありますので、そちらを使いましょう。
余談ですが、これのおかげで複数のプログラムから同時にinsertしても問題無いんです。

2022-05-11 14:28 UTC, choco0809 commented on memo.rb
> +def add_memo(params)
シリアル値をすっかり失念していました🙇‍♂️
> 余談ですが、これのおかげで複数のプログラムから同時にinsertしても問題無いんです

初めて知りました。業務で使用しているDBではシリアル値のように自動的に採番してくれる項目を保持しているのをみたことながく、実際に自動的に採番されるとどういうメリットがあるのか理解できていなかったため、非常に参考になります！

2022-05-12 01:29 UTC, u1tnk approved these changes

2022-05-20 23:39 UTC, merged